version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:8.0.9
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:22.15.1
    working_dir: /usr/src/api
    command: bash -c "npm install --only=prod && npm run docker-debug"
    volumes:
      - ./dist:/usr/src/api/dist
      - ./package.json:/usr/src/api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      MONGO_URL: "mongodb://mongo:27017/"
