version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:8.0.9
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:22.15.1
    working_dir: /usr/api
    volumes:
      - ./src/:/usr/api/src
      - ./package.json:/usr/api/package.json
      - ./tsconfig.json:/usr/api/tsconfig.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - mongo
    env_file:
      - ./.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MONGO_URL: "mongodb://mongo:27017/"
    command: bash -c "npm install && npm run docker:start-debug"
